name: Test & Report

on:
  pull_request:
  push:
permissions:
  id-token: write
  contents: read
  checks: write
  statuses: write
jobs:
  test:
    name: Test & Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Run Flutter Test
        run: flutter test --machine > test-results.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: test-results.json
          reporter: dart-json
